spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${REMOTE_DATABASE_URL:jdbc:postgresql://localhost:5432/railway}
    username: ${REMOTE_DATABASE_USERNAME:postgres}
    password: ${REMOTE_DATABASE_PASSWORD:admin}

  flyway:
    baseline-on-migrate: true

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: testforuniversity.1@gmail.com
    password: ryslrzkeqgaffqci
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8082

liqpay:
  key:
    public: sandbox_i23623612477
    private: sandbox_AdLWmfil38qP9jQ8A707aVFOM5gmZf2fJiUa0eRy
